### ISSUE TITLE
Repository not syncing

### ISSUE THREAD

**Issue by xfim** [chadmed/asahi-overlay#1]
Dear @chadmed ,

I am trying to use the repository to be able to access the asahi sources, but neither in a MacStudio nor in my regular Gentoo installation I am able to sync.

I add the `asahi.conf` file under `/etc/portage/repos.conf/` as it is in the repository, but running
```
emaint sync -r asahi
```

gets stuck in "Cloning into '.'..." and after more than two minutes ends with "fatal: unable to connect to github.com".

As mentioned, this happens also when using git clone as a regular user with the credentials in github (if that would be useful).

Thank you.

**Comment by chadmed** [comment]
in repo.conf, change git:// in the URL to https://. Not sure why it's like that. Will push a fix to asahi-gentoosupport.
