### ISSUE TITLE
 mesa 24.2.0_pre20240727 without egl wayland?

### ISSUE THREAD

**Issue by aladmit** [chadmed/asahi-overlay#101]
Does mesa-24.2.0_pre20240727(~arm64) work on your machine? I tried it today and DE(Cosmic) fails to start with it. I see a bunch of errors saying that EGL_WL_bind_wayland_display extension is not supported.

Rolled back. Everything works on mesa-24.2.0_pre20240725-r1 and DE finds this extension.

package flags:
```
USE="X llvm (opengl) proprietary-codecs vulkan wayland zstd (-d3d9) -debug -lm-sensors (-opencl) -osmesa (-selinux) -test -unwind -vaapi -valgrind (-vdpau) -vulkan-overlay -xa"
LLVM_SLOT="18 -17"
VIDEO_CARDS="asahi"
```

Makeopts:
```
WARNING_FLAGS="-Werror=odr -Werror=strict-aliasing"
COMMON_FLAGS="-O2 -pipe -flto ${WARNING_FLAGS}"
```

**Comment by jannau** [comment]
It needs `asahi-sources-6.9.12_p1.ebuild` /  `asahi-kernel-6.9.12_p1.ebuild` or later. There was an incompatible change in the GPU userspace API and only those are compatible.

**Comment by aladmit** [comment]
Interesting, thanks for helping me out. I would never figure this out myself :)

I see that `asahi-sources-6.9.12` already installed but it isn't selected, so mesa was build with `asahi-sources-6.9.12`.

**Comment by jannau** [comment]
This is a runtime issue not a build time issue. Boot into 6.9.12 and mesa-24.2.0_pre20240727 will work

**Comment by hexchain** [comment]
It seems `asahi-kernel-6.9.12_p1.ebuild` is not yet available in the overlay?

**Comment by aladmit** [comment]
Tested with 6.9.12 kernel. It works 👍🏼
