### ISSUE TITLE
Firefox not launching, GPU problem

### ISSUE THREAD

**Issue by dxwil** [chadmed/asahi-overlay#102]
Yesterday after a random reboot Firefox randomly stopped launching normally. It gave me some error about `libva-drm.so.2 is missing`. I then installed the Firefox rapid release instead of esr as well as updated both the kernel and mesa to the latest testing release. Firefox still doesn't launch but gives me a different error now: `CrashAnnotation GraphicsCriticalError: [0] [GFX-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=6.77899) [GFX-]: RenderCompositorSWGL failed mapping default framebuffer, no dt`. I assume it's related to mesa, but I dont understand what changed between those reboots and made Firefox not launch.

**Comment by chadmed** [comment]
Can you please run asahi-diagnose and link to the output?

**Comment by dxwil** [comment]
Posting it here as well to keep track https://bpa.st/QHRA

**Comment by dxwil** [comment]
I couldn't solve this in the end and switched to NixOS, so not really a solution but we can't diagnose anything further
