### ISSUE TITLE
sys-apps/speakersafetyd Fails to Build

### ISSUE THREAD

**Issue by Venator777** [chadmed/asahi-overlay#105]
In trying to install asahi-audio, the sys-apps/speakersafetyd emake fails. Relevant logs: 

emerge --info: https://pastebin.com/isAcwipX
build log: https://pastebin.com/f3ZgkPam
ebuild enviornment: https://pastebin.com/j6zukv35

Similar issue occurs for media-libs/bankstown-lv2.

**Comment by chadmed** [comment]
Please resync and try again. Had to make a couple of changes to accommodate the `cargo.eclass` changes in `::gentoo`

**Comment by Venator777** [comment]
Works for media-libs/bankstown-lv2 now but speakersafetyd still runs into the same error.

**Comment by chadmed** [comment]
Delete `/var/db/pkg/sys-apps/speakersafetyd/` and try again

**Comment by Venator777** [comment]
Works now, thanks!
