### ISSUE TITLE
 * ERROR: sys-kernel/asahi-kernel-6.10.5_p1::asahi failed (compile phase):

### ISSUE THREAD

**Issue by sithmike** [chadmed/asahi-overlay#107]
kernel (on ~arm64) fails to compile successfully

[info.txt](https://github.com/user-attachments/files/16738913/info.txt)
[pqv.txt](https://github.com/user-attachments/files/16738914/pqv.txt)

# LD [M]  net/qrtr/qrtr.ko
  aarch64-unknown-linux-gnu-ld.bfd -r -EL  -maarch64elf -z noexecstack --no-warn-rwx-segments --build-id=sha1  -T scripts/module.lds -o net/qrtr/qrtr.ko net/qrtr/qrtr.o net/qrtr/qrtr.mod.o
# LD [M]  net/qrtr/qrtr-smd.ko
  aarch64-unknown-linux-gnu-ld.bfd -r -EL  -maarch64elf -z noexecstack --no-warn-rwx-segments --build-id=sha1  -T scripts/module.lds -o net/qrtr/qrtr-smd.ko net/qrtr/qrtr-smd.o net/qrtr/qrtr-smd.mod.o
# LD [M]  net/qrtr/qrtr-mhi.ko
  aarch64-unknown-linux-gnu-ld.bfd -r -EL  -maarch64elf -z noexecstack --no-warn-rwx-segments --build-id=sha1  -T scripts/module.lds -o net/qrtr/qrtr-mhi.ko net/qrtr/qrtr-mhi.o net/qrtr/qrtr-mhi.mod.o
make[1]: *** [/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/work/linux-6.10/Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/work/build'
make: *** [Makefile:240: __sub-make] Error 2
 * ERROR: sys-kernel/asahi-kernel-6.10.5_p1::asahi failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=sys-kernel/asahi-kernel-6.10.5_p1::asahi'`,
 * the complete build log and the output of `emerge -pqv '=sys-kernel/asahi-kernel-6.10.5_p1::asahi'`.
 * The complete build log is located at '/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/work/linux-6.10'
 * S: '/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/work/linux-6.10'

i have the complete build.log, but seems it's too big for github

**Comment by chadmed** [comment]
Please post build.log to a paste site and link it

**Comment by sithmike** [comment]
sorry, didnt find any place that accepts a 65mb text file, so i'll do it like this

https://drive.google.com/file/d/1tcHqOgIs9O2DL3-rHT3ovSHVpqN-ru0H/view?usp=sharing

**Comment by chadmed** [comment]
This is the important section:

```
+ btf_vmlinux_bin_o=
+ is_enabled CONFIG_DEBUG_INFO_BTF
+ grep -q '^CONFIG_DEBUG_INFO_BTF=y' include/config/auto.conf
+ btf_vmlinux_bin_o=.btf.vmlinux.bin.o
+ gen_btf .tmp_vmlinux.btf .btf.vmlinux.bin.o
+ local pahole_ver
++ command -v pahole
+ '[' -x '' ']'
+ echo 'BTF: .tmp_vmlinux.btf: pahole (pahole) is not available'
BTF: .tmp_vmlinux.btf: pahole (pahole) is not available
+ return 1
+ echo 'Failed to generate BTF for vmlinux'
Failed to generate BTF for vmlinux
+ echo 'Try to disable CONFIG_DEBUG_INFO_BTF'
Try to disable CONFIG_DEBUG_INFO_BTF
+ exit 1
make[3]: *** [/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/work/linux-6.10/scripts/Makefile.vmlinux:34: vmlinux] Error 1
make[2]: *** [/var/tmp/portage/sys-kernel/asahi-kernel-6.10.5_p1/work/linux-6.10/Makefile:1170: vmlinux] Error 2
```

Do you have a savedconfig that is trying to enable debug stuff without pahole being installed?

**Comment by sithmike** [comment]
No, i never compiled my own kernel, use dist-kernel, and it always worked

(Thanks for looking into it, im not an expert, but i really love gentoo)

**Comment by jannau** [comment]
`CONFIG_DEBUG_INFO_BTF=y` comes from the fedora config and we simply missed `pahole` as dependency.

**Comment by chadmed** [comment]
Please resync and try again, I've pushed a patch to disable this config option if `USE="-debug"`

**Comment by sithmike** [comment]
thanks for your hard work.... but seems it made things worse
[build.log](https://github.com/user-attachments/files/16742462/build.log)

**Comment by sithmike** [comment]
Success! Cheers mate
