### ISSUE TITLE
llvm toolchain: sys-kernel/asahi-kernel-6.10.5_p1 amdgpu fails and stops the compilation

### ISSUE THREAD

**Issue by Zuccace** [chadmed/asahi-overlay#113]
Hi, and sorry not providing much information here (yet).
But I was unable to compile sys-kernel/asahi-kernel-6.10.5_p1.
I quickly grepped trough the build log and saw that it failed at compiling amdgpu.
I use llvm toolchain (with glibc) on this M2 Air as I though using llvm and friends to compile stuff on M2 could be beneficial, since that's what Apple uses in their development environment.

My fix currently is to create **/etc/kernel/config.d/00_diable_amdgpu.config**
```
# CONFIG_DRM_AMDGPU is not set
# CONFIG_DRM_AMDGPU_SI is not set
# CONFIG_DRM_AMDGPU_CIK is not set
# CONFIG_DRM_AMDGPU_USERPTR is not set
# CONFIG_DRM_AMDGPU_WERROR is not set
```

If needed I can remove that config snippet and reproduce the exact error and upload build.log somewhere.

**Comment by chadmed** [comment]
Huh, thought I had fixed this a while ago. Should be fixed now if you resync and try to emerge again :)

**Comment by Zuccace** [comment]
**sys-kernel/asahi-kernel-6.10.7_p2-r1** did compile fine.
