### ISSUE TITLE
mesa-20241006 ready for vulkan

### ISSUE THREAD

**Issue by xfim** [chadmed/asahi-overlay#119]
Dear @chadmed ,

Is it the mesa-20241006 the first release with vulkan? I can't seem to see in the ebuild that it is using vulkan when the card is asahi. Is it expected eventually?

Thank you,

**Comment by chadmed** [comment]
It is customary for every driver to have a VIDEO_CARDS USE_EXPAND. You will notice there is now a `honeykrisp` option for VIDEO_CARDS. Set it in `/etc/portage/make.conf` and re-emerge Mesa.
