### ISSUE TITLE
`git` going brrr when trying to clone the mesa source code.

### ISSUE THREAD

**Issue by monomycelium** [chadmed/asahi-overlay#13]
while i was trying to merge asahi's fork of mesa with their gpu stuff, i got this error:

```
fatal: update_ref failed for ref 'refs/git-r3/media-libs/mesa/0/__main__': cannot update ref 'refs/git-r3/media-libs/mesa/0/__main__': trying to write ref 'refs/git-r3/media-libs/mesa/0/__main__' with nonexistent object 7be6b639a915d66fab9069a2b42e6194ed0d1fb2
```

i hope this can be fixed soon. if you want, i can give you more information and stuff.

**Comment by monomycelium** [comment]
i was initially trying to merge `mesa-23.0.0_pre20221209`, then I tried all the other ebuilds, but none of them worked except the older `mesa-23.0.0_pre20221205`. it seems that a branch or something, `7be6b639a915d66fab9069a2b42e6194ed0d1fb2`, is missing. i really want to try out gentoo with asahi's gpu drivers.

**Comment by chadmed** [comment]
@jannau good idea, i've taken care of it.

@monomycelium you're basically on your own with this sort of thing, sorry. This is still very early days and Lina's work
moves fast, and we are at her mercy when it comes to packaging the right stuff. I try to keep on top of everything
to the best of my ability, but tracking such a fast-moving target is difficult when it's not your full time job.

If you're not comfortable with editing the ebuild occasionally when we fall out of sync with upstream, then I suggest
waiting just a little while longer for GPU support until things settle down a bit. Of course if you are comfortable
with the ebuild development cycle, you are always welcome to submit patches :)

**Comment by monomycelium** [comment]
Ah, I see. Thank you. I figured out that the `ebuilds` in this overlay are based on official `ebuilds` are based on `PKGBUILDs` the [AsahiLinux/PKGBUILDs](/AsahiLinux/PKGBUILDs) repository (as well as official `ebuilds`).

**Comment by monomycelium** [comment]
Unfortunately, I cannot start Wayland session for KDE Plasma with the newer Mesa stuff. I guess it just isn't ready yet, so we shall part ways for now, Gentoo. Anyway, I hope these experimental (but cool, huh?) stuff can be sorted out (and even merged with upstream projects!). Regardless, kudos to everyone involved in the Asahi project, for working tirelessly and hard to get hardware from mad corporations working with the world of open-source, where everything comes with good intention!

**Comment by chadmed** [comment]
Just finished doing that actually. Been meaning to do so for a while. Resync the Asahi overlay and it should be good to go provided you have the package unmasked.

**Comment by monomycelium** [comment]
Thanks! Have you gotten the GPU stuff working on Gentoo?

**Comment by chadmed** [comment]
I'm using it as we speak! You have to have your rust tooling set up properly for kernel builds and our mesa unmasked of course. Pop in on `#asahi-alt` for more help.

**Comment by monomycelium** [comment]
Great! I'll try it out soon.

**Comment by monomycelium** [comment]
I found a bug in the `ebuild`:
```
 *   The source directory '/var/tmp/portage/media-libs/mesa-23.0.0_p2/work/mesa-23.0.0-p2' doesn't exist
```

This happens because the archive was extracted to `/var/tmp/portage/media-libs/mesa-23.0.0_p2/work/mesa-asahi-20221229`.

**Comment by monomycelium** [comment]
Can we get a detailed guide on how to set the GPU drivers up? I'm struggling.

**Comment by monomycelium** [comment]
I got this error:
```
asahi ~ # emerge --ask media-libs/mesa::asahi

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 6.18 s.

[ebuild     U *] media-libs/mesa-23.0.0_p2 [22.2.5] VIDEO_CARDS="asahi%*" 

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

media-libs/mesa:0

  (media-libs/mesa-23.0.0_p2:0/0::asahi, ebuild scheduled for merge) USE="X gles2 llvm proprietary-codecs wayland zstd (-d3d9) -debug -gles1 -lm-sensors (-opencl) -osmesa (-selinux) -test -unwind -vaapi (-valgrind) (-vdpau) -vulkan -vulkan-overlay -xa -zink" VIDEO_CARDS="asahi (-d3d12) -freedreno (-intel) -lima -nouveau -panfrost (-r300) (-r600) (-radeon) (-radeonsi) -v3d -vc4 -virgl -vivante (-vmware)" pulled in by
    (no parents that aren't satisfied by other packages in this slot)

  (media-libs/mesa-22.2.5:0/0::gentoo, installed) USE="X gles2 llvm proprietary-codecs wayland zstd (-d3d9) -debug -gles1 -lm-sensors (-opencl) -osmesa (-selinux) -test -unwind -vaapi (-valgrind) (-vdpau) -vulkan -vulkan-overlay -xa -xvmc -zink" VIDEO_CARDS="(-d3d12) -freedreno (-intel) -lima -nouveau -panfrost (-r300) (-r600) (-radeon) (-radeonsi) -v3d -vc4 -virgl -vivante (-vmware)" pulled in by
    (no parents that aren't satisfied by other packages in this slot)


!!! Enabling --newuse and --update might solve this conflict.
!!! If not, it might help emerge to give a more specific suggestion.
```

Do you know what went wrong? I've already unmasked the package by letting it accept `**` as its keyword.

**Comment by monomycelium** [comment]
Solved by removing `mesa` from `/var/lib/portage/world` or using `--backtrace=30`. However, Mesa still does not work for me!
