### ISSUE TITLE
Unable to build `media-libs/mesa-25.0.0_pre20241204::asahi` after LLVM ebuild move in `::gentoo`

### ISSUE THREAD

**Issue by demize** [chadmed/asahi-overlay#134]
Today, Gentoo implemented a change to how `llvm` ebuilds are organized: as part of this, they [moved `sys-devel/llvm` to `llvm-core/llvm`](https://github.com/gentoo/gentoo/commit/1f9f1999cdc8ccb94054dec2d2951c7e486aa996). Because of this change, `media-libs/mesa::asahi` now depends on a package that no longer exists, and thus its dependency graph cannot be solved:

```
emerge: there are no ebuilds to satisfy "sys-devel/llvm:19[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_s390_32(-)?,abi_s390_64(-)?]".
(dependency required by "media-libs/mesa-25.0.0_pre20241204::asahi" [ebuild])
(dependency required by "x11-libs/gtk+-3.24.41-r1::gentoo[wayland]" [installed])
(dependency required by "x11-themes/adwaita-icon-theme-45.0::gentoo" [installed])
(dependency required by "gui-libs/gtk-4.14.4-r1::gentoo" [installed])
(dependency required by "app-crypt/gcr-4.2.1::gentoo[gtk]" [installed])
(dependency required by "app-crypt/pinentry-1.3.1::gentoo[gtk]" [installed])
(dependency required by "app-crypt/gnupg-2.4.6-r1::gentoo" [ebuild])
(dependency required by "app-portage/gemato-20.6::gentoo[gpg]" [installed])
(dependency required by "sys-apps/portage-3.0.66.1-r1::gentoo[rsync-verify,-build]" [installed])
(dependency required by "app-admin/perl-cleaner-2.31-r2::gentoo[-pkgcore]" [installed])
(dependency required by "dev-lang/perl-5.40.0::gentoo[-minimal]" [installed])
(dependency required by "x11-misc/xkeyboard-config-2.43::gentoo" [ebuild])
(dependency required by "x11-libs/libxkbcommon-1.7.0-r1::gentoo" [installed])
```

I believe this should be solvable (heh) by adjusting the RDEPEND to reflect the moves today; it may require a few packages to be updated, as a good number were moved.

**Comment by chadmed** [comment]
Already on it :)

**Comment by chadmed** [comment]
Should be sorted now if you resync the overlay. If you used `eselect repository` to enable it, there's a chance that you're syncing with the Gentoo mirror. If that is the case, please change the remote/sync URI to https://github.com/chadmed/asahi-overlay in `/etc/portage/repos.conf/asahi.conf` and then sync again.

**Comment by demize** [comment]
Looks like it's solved!
