### ISSUE TITLE
Does this overlay provide mesa with M1 GPU support? 

### ISSUE THREAD

**Issue by playXE** [chadmed/asahi-overlay#17]

**Comment by chadmed** [comment]
Yes, you need to build the kernel with Rust and install the provided Mesa package.

**Comment by ezntek** [comment]
USE="rust symlink" doesn't work. I've also installed media-libs/mesa::asahi, also doesn't work. I have an M1 MacBook Pro, if that helps. The new backlight driver also doesn't work.

**Comment by ezntek** [comment]
One has to also fetch the edge config from the linux-asahi-edge PKGBUILD from the asahi pkgbuilds repo. Then, one can append the contents of that file into the existing config to set the new edge features. I did that, and things like suspend and the backlight driver worked, but the GPU driver still doesn't work. I did emerge `media-libs/mesa::asahi`, though.

**Comment by AmateurECE** [comment]
@ezntek I believe I followed you here from your reddit thread :smile:. Ensure that `CONFIG_DRM_ASAHI` is set in your running config. Building the kernel with Rust support requires some special considerations on Gentoo, and if this is not done, attempting to build the Asahi DRM driver will not succeed.

Additionally, the `VIDEO_CARDS: asahi` USE flag is not set by default for the `media-libs/mesa::asahi` package in the overlay, so please ensure that's set for you.

**Comment by ezntek** [comment]
I did reply to you (perhaps, idk), the config options unset themselves after i run make. In trying to fiddle, i messed up my modules folder, so now my system is unbootable (i dont have a backup kernel ._.)

Chrooting would take a while, as one would have to build an asahi kernel on another machine and inject it into a live USB stick.

I'll try 2 weeks later, I have my final exams soon, but itd be great if you could outline what you did to get it working (for future reference, help would be greatly appreciated). Ive set VIDEO_CARDS and all that fun stuff, to no avail.
