### ISSUE TITLE
Patches fail

### ISSUE THREAD

**Issue by xfim** [chadmed/asahi-overlay#2]
While emerging asahi-overlay the application of patches fails:

```
patching file sound/soc/apple/mca.c
Hunk #1 FAILED at 120.
1 out of 1 hunk FAILED -- saving rejects to file sound/soc/apple/mca.c.rej
patching file sound/soc/apple/mca.c
Hunk #1 FAILED at 914.
Hunk #2 FAILED at 948.
1 out of 1 hunk FAILED -- saving rejects to file sound/soc/apple/mca.c.rej
```

Any  guess why this may be?
Thank you very much.

**Comment by chadmed** [comment]
yeah we merged the MCA driver into the main branch a while ago and I hadn't gotten around to removing the patch from the ebuild. should be fixed for you now if you resync the overlay.

**Comment by xfim** [comment]
Dear @chadmed ,

Thank you very much for the explanation. I managed to simply comment the patch line in the ebuild, and proceeded. Now it is perfect because it is properly fixed.
