### ISSUE TITLE
How to properly update all Asahi related packages

### ISSUE THREAD

**Issue by xfim** [chadmed/asahi-overlay#26]
Dear all,

I am not sure if this is the correct place to ask this, so feel free to address me somewhere else.

I installed gentoo on a Mac Studio about a year ago, following the tutorial of installing gentoo with LiveCD, and since then I have done the regular updates, but nothing "serious", like the kernel, mesa for GPU, etc... Now it is time to do it properly, but I really don't know where to start and how to proceed, specially since I would like to avoid having an unbootable system.

The situation is the following:

- MAC OS was updated a while ago. 
- `u-boot` is `9999` as gentoo package, but since I don't know exactly how u-boot works, I am not sure the "u-boot" booting my system is indeed this one, or if I should do something more
- The kernel is `5.19.0-asahi-ARCH`
- mesa is `23.0.0_pre20230606` from the asahi repository, but VIDEO_CARDS does not have "asahi"

What I would like to achieve is a system that has a more recent kernel (I believe this would mean I have the USB ports working, for instance), and GPU support. But I am terrified of making a bad move and ending up needing to reinstall all again, since this is my main system and works so far.

Questions:

- Should I first check and update MAC OS?
- Should I update u-boot? How?
- Is it safe to update firmware with `fwupd`
- In which order do I need to proceed?
- I have read that the kernel config needs to be manually edited and rust enabled (see #17 ). What would be the way to safely update the kernel in order to achieve that?
- For the GPU support, can I simply emerge mesa with VIDEO_CARDS="asahi" and expect that all will work (provided that the kernel is updated properly)? 
- Should I move to wayland also?
- Do I have to take special care in grub?
- What is the order in which all must be performed?

In return, I can commit to add a wiki page explaining carefully the steps and tips that you have provided.

Thank you in advance,

**Comment by chadmed** [comment]
1. Yes, there are some SMC features that rely on the global firmware being updated by macOS
2. `emaint -r asahi sync && emerge -auvDN @world && update-m1n1`
3. None of our firmware is updated by `fwupd` - use `asahi-fwupdate` 
4. The order doesn't _really_ matter, but `update-m1n1` expects compiled DTBs in `/usr/src/linux/arch/arm64/boot/dts/apple/` so you should do the kernel first
5. You need to ensure that `RUST=y` and `DRM_ASAHI=m` and `DRM_APPLE=m`. How you satisfy the requirements for those flags is an exercise for the reader.
6. Yes
7. Yes, X11 is known to be subtly broken and we no longer support it
8. Nope, update GRUB like you normally would
9. Update macOS, update overlay, run system update, do `asahi-fwupdate`, get kernel built with new options enabled, update GRUB, should be good to go

**Comment by xfim** [comment]
That is extremely useful and precise. Thank you very much @chadmed . Maybe some of it can be directly added to the main readme.

**Comment by chadmed** [comment]
Changing graphics settings through `/etc/m1n1.conf` is no longer supported since we have DCP. Don't use it.

As for Bluetooth, I can't see anything in that `asahi-diagnose` dump that would  cause Bluetooth to stop working. Ensure
that the `bluetooth` service  is started and your kernel is configured properly.

`asahi-fwupdate` does not actually pull new firmware from macOS, it just pulls firmware from that tarball into `/lib/firmware` for newly enabled devices.

**Comment by xfim** [comment]
Thank you, @chadmed , for taking some time to go through it. I was precisely now checking other possibilities (https://github.com/chadmed/asahi-overlay/commit/a48f76ee44a0d396812fec8dc29dfc9e89ea554a), and I have seen that the symlink from "/usr/bin/update-vendor-firmware" to "/usr/local/bin/update-vendor-firmware" is broken because the latest is not present. Maybe this could be a clue?

In any case, the "OS firmware" in the previous message was at 12.3. Isn't this a problem?  Should it be the same as the SFR? Or another possibility: how can I update the tarball in /lib/firmware to the latest, so that when I do `asahi-fwupdate` it uses the latest firmware? 

Another clue maybe exists in dmesg, in case it helps:

```
[    4.320429] hci_bcm4377 0000:01:00.1: Unable to load firmware; tried 'brcm/brcmbt4387c2-apple,okinawa-u.bin' and 'brcm/brcmbt4387c2-apple,okinawa.bin'                                                                                                                                                                                                  
[    4.320432] hci_bcm4377 0000:01:00.1: Failed to load firmware 
```

**Comment by jannau** [comment]
There seems to be an issue with the bt firmware not being present. I think the installer should have always extracted that. Please check that `/boot/efi/vendorfw/firmware.tar` contains it. Does `/boot/efi/vendorfw/firmware.cpio`
 exists? `asahi-fwupdate` will extract and generate those archives from the files in `/boot/efi/asahi`.
How do you boot/generate the initrd? If it's not dracut or not using initrds at all the issue is most likely that the firmware is missing. Does `/lib/firmware/vendor` exists and has all the files from  `/boot/efi/vendorfw/firmware.tar`?

If you're using dracut, is `sys-apps/asahi-scripts` installed? If not you will need to ensure that your initramfs does the same as https://github.com/AsahiLinux/asahi-scripts/tree/main/dracut/modules.d/99asahi-firmware

I really recommend to follow this method. If you just extract the firmware into `/lib/firmware` you will run into problems when additional firmware is needed.

**Comment by xfim** [comment]
1. According to my knowledge, there is bt firmware in `/boot/efi/vendorfw/firmware.tar`:
[see pastebin](https://termbin.com/85r5s). md5sum is `7f281efa717227c10f0cb0a89f2fda17`.

2. `/boot/efi/vendorfw/firmware.cpi` does exist with md5sum `ba6b8690d643b715dc5617e705b00180`.

3. I generate initrd using `genkernel all`.

4. `/lib/firmware/vendor` does not exist. But under `/lib/firmware` I can see for instance the first file that exists in `firmware.tar`. Not sure, though, if it is the same file. Only that it has the same name (`/lib/firmware/brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.3.txt`).

5. I am not using dracut, but genkernel. Do you advise to move to dracut instead of genkernel?. I am not familiar with dracut. In fact, for genkernel, I had to add `CMD_CALLBACK=make dtbs` to the options to make it work. Would dracut make my life easier? Now, after the kernel configuration, I only need to do `genkernel all` and `grub-mkconfig -o /boot/grub/grub.cfg` and all is taken care of. Would dracut make my life easier?

6. `sys-apps/asahi-scripts-20230606::asahi` is installed. And now I see that there are  files under `/usr/lib/dracut` that are specific to asahi.

Sorry for such a specific problem. And thank you very much for your support.

**Comment by xfim** [comment]
Yes, yes. That worked. I understand it is not very elegant, but that worked quite well. The only thing is that now when creating the initram file with all the firmware it takes about 20 seconds to start. I have linux-firmware, just in case, and that may be taking a lot of space. Is it safe to remove it?

Thank you again for everything. All works perfectly. The color, the GPU, bluetooth, USBs, all.
