### ISSUE TITLE
qualify if llvm is really needed for asahi VIDEO_CARD

### ISSUE THREAD

**Issue by Kokokokoka** [chadmed/asahi-overlay#49]
If one uses rust-gpu for asahi, mesa should work even without llvm (more than that, it works without llvm flag). 
why is llvm dependency added?

**Comment by jannau** [comment]
I was mistaken and llvm/spirv/libclc are only build dependencies

**Comment by jannau** [comment]
I changed `libclc` to a build dependency but I won't touch llvm. It is an build dependency but I would prefer not to touch the complicated dependency handling for llvm

**Comment by Kokokokoka** [comment]
dunno why, it is working without llvm dep (i remove manually it every time)
