### ISSUE TITLE
Package krunvm

### ISSUE THREAD

**Issue by marco-04** [chadmed/asahi-overlay#63]
krunvm and libkrun are not packaged in Gentoo, so it would be very handy for them to be packaged at least here in the overlay

**Comment by chadmed** [comment]
Please read the commit log.

Sergio's been developing most of the Asahi-specific stuff in private branches and committing builds directly to his COPR. The upstream krunvm infrastructure is entirely useless for our use case in its current state, and pulling random tarballs from URLs extracted from Fedora build logs is not a stable or maintainable way to package software. Until Sergio changes this unfortunate development model or upstreams the functionality relevant to Asahi, we can't really do anything.

**Comment by marco-04** [comment]
Oh sorry, I didn't notice it. That's unfortunate, and I hope this gets sorted out soon. Thanks for the reply!
