### ISSUE TITLE
No GPU acceleration after update to mesa-24.1.0_pre20240228-r1

### ISSUE THREAD

**Issue by xfim** [chadmed/asahi-overlay#67]
I just performed an update and noticed that while mesa was updated from mesa-24.0.0_pre20231213 I have lost GPU acceleration. 

I have updated many times mesa without having to update the kernel at the same time, and never noticed a loss in GPU acceleration.

I am using kernel 6.6.0-asahi-14-arm64. Should I update to 6.6.0-asahi-15? The trouble is that when trying to do so genkernel does not finish and is stuck in "appending firmware cpio data", which never happened so far. 

So before dealing with genkernel I would like to ask if there is something in mesa-24.1.0 that makes it dependent on kernel 6.6.0-asahi-15 and not 14, to know where do I start.

Thank you very much.

**Comment by jannau** [comment]
yes, 6.6.0-asahi-15 has an UAPI change in the kernel GPU and only mesa versions mesa-24.1.0_pre20240118 and later are compatible with that.

**Comment by xfim** [comment]
OK, @jannau , thank you for the clarification. Do you, by chance, happen to know if there is something else in 6.6.0-asahi-15 that could make genkernel break at 

```
*         >> Appending firmware cpio data ...

* ERROR: modinfo error!
```

**Comment by chadmed** [comment]
Please just use dracut, genkernel is just broken and upstream are transitioning to dracut too.

**Comment by xfim** [comment]
OK. That seemed difficult but was fairly easy. All well there, 6.6.0_asahi_15 running and GPU acceleration working. Thank you all.
