### ISSUE TITLE
asahi-kernel requires rust with rust-src USE flag, but rustfmt is also needed

### ISSUE THREAD

**Issue by NyaomiDEV** [chadmed/asahi-overlay#68]
Compiling asahi-kernel just to be in line with everyone else; the dependency it requires is rust and rust-bin with `rust-src` USE flag; understandable. However, it will fail compilation because it won't find `rustfmt` in PATH: it's not installed unless the user called for it!

This should probably be specified as required in the ebuild.

**Comment by chadmed** [comment]
Fixed with `sys-kernel/asahi-kernel-6.6.0_p15-r1`
