### ISSUE TITLE
`asahi-kernel-6.6.0_p15` fails to build with `=dev-lang/rust-1.75.0`

### ISSUE THREAD

**Issue by demize** [chadmed/asahi-overlay#69]
I believe it fails during `bindgen`, though I'm not 100% sure how to interpret the logs ([asahi-kernel-6.6.0_p15.build.log](https://github.com/chadmed/asahi-overlay/files/14733645/asahi-kernel-6.6.0_p15.build.log)).

With dev-lang/rust-1.75.0 just promoted to stable yesterday, this might be a significant issue.

**Comment by NyaomiDEV** [comment]
downgrade to 1.74.1 for now... rip

**Comment by demize** [comment]
Yeah, I downgraded to 1.74.1 built the kernel, then updated `@world`. Works fine until I have to build the kernel again, and then I may need to downgrade again (but hopefully this is fixed before then!).

**Comment by demize** [comment]
tpwrules is using this patch on top of 6.6-asahi15 on NixOS, which may be required to get the kernel building here too: https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/linux-asahi/0001-check-in-new-alloc-for-1.75.0.patch

Not sure if this can just be applied with emerge, or if it would need some sort of changes first.

**Comment by chadmed** [comment]
Should be fixed with `sys-kernel/asahi-kernel-6.6.0_p15-r2`

**Comment by demize** [comment]
Looks fixed from my end, thanks!
