### ISSUE TITLE
`vfat` isn't loaded with `asahi-kernel-6.6.0_p16`

### ISSUE THREAD

**Issue by NyaomiDEV** [chadmed/asahi-overlay#73]
Throwing in this issue here as to find others who have the same issue after updating.

Symptoms:
- `ESP` is not mounted at boot
- `modprobe vfat` is necessary to mount it afterwards
- Early `/lib/firmware/vendor` bind-mounting fails
  - Wifi doesn't work

Observations:
- `vfat.ko` is included in initramfs

**Comment by NyaomiDEV** [comment]
As a workaround, you can use `rd.driver.pre=vfat` as a kernel commandline argument

**Comment by jannau** [comment]
do `modules.dep` and `modules.symbols` exists in `/lib/modules/6.6.0-asahi-16-dist` (for gentoo-kernel-6.6.0_p16-r1)?

**Comment by NyaomiDEV** [comment]
I didn't look at those files honestly, but this issue seems to be fixed in p16-r1. Closing.
