### ISSUE TITLE
Invalid download path for sys-boot/u-boot

### ISSUE THREAD

**Issue by schkwve** [chadmed/asahi-overlay#80]
Hi,
I'm currently stuck when installing Gentoo on my M1 MacBook Air.
I've tried to install U-Boot (which appears to be part of `sys-apps/asahi-meta`), but I kept getting a 404 Not Found response. After closer examination I have found out that Portage tries to download the latest tarball named `u-boot-v2023.07.02-p4.tar.gz`, meanwhile the **actual** name is `asahi-v2023.07.02-4.tar.gz` (full GitHub URL was left out).

Does anyone else have this issue as well, or was it something I did to trigger this issue?

Thank you for your response,
Jozef

**Comment by jannau** [comment]
Indeed, will be fixed by #81, thanks for reporting

**Comment by schkwve** [comment]
Awesome, thanks for the quick fix!
