### ISSUE TITLE
can't download kernel config

### ISSUE THREAD

**Issue by sithmike** [chadmed/asahi-overlay#99]
during a system upgrade (~arm64) it errors out with a checksum failure
[build.log](https://github.com/user-attachments/files/16234954/build.log)

**Comment by chadmed** [comment]
My local distfile cache must have gotten out of sync somehow. Should be sorted with new Manifest if you resync.

**Comment by jannau** [comment]
> My local distfile cache must have gotten out of sync somehow. Should be sorted with new Manifest if you resync.

I think I just forgot to update the fedora config ver when I added 6.9.9_p4 (and then copied to 6.9.9_p5) and `pkgdev commit` hides the fact that it updated an existing file in the Manifest. Fix looks correct, thanks.
